### ISSUE TITLE
Erratic behavior in autocorrect for deletetag command

### ISSUE THREAD

**Issue by lancehaoh** [CS2103AUG2017-W11-B1/main#165]
Input "deletetaa friends" is autocorrected to "deletetag friends" but input "aeletetag friends" is treated as unknown command. Both have edit distance of 1. Why are they handled differently?

**Comment by JYL123** [comment]
I will preprocess the first alphabet to reduce the processing time to autocorrect a command. I have this consideration is because it has very low chance that the first input alphabet is wrong, usually the first input alphabet is correct while the subsequent alphabets are wrong unless we deliberately typed the first letter wrongly.

**Comment by lancehaoh** [comment]
Alright. Please remember to document this setting in the developer and user guide, if it wasn't already stated.
